title: Samuel Dribsa # your name (or website title) here
logo: "/images/logo_sami.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Welcome! I am a seasoned professional skilled in harnessing data to drive impactful decisions in healthcare management. With a proven track record in health information systems and analytics, I've delivered comprehensive reports on health activities, integrated systems for strategic planning, and enhanced patient services through meticulous analysis.

My background spans managing ART registration, overseeing pharmaceutical services, evaluating community health information systems, and maintaining crucial HIV-related data. This expertise intersects with technical prowess in database management, troubleshooting, and network maintenance.

Let's connect and explore how my experience in leveraging data-driven insights can propel success and innovation in healthcare analytics and decision-making.<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
