title: Samuel Dribsa # your name (or website title) here
logo: "/images/logo_sami.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Greetings! I'm a seasoned healthcare management professional skilled in data-driven decision-making. With expertise in health information systems, analytics, and a track record of delivering impactful reports, I excel in strategic planning and enhancing patient services. My background includes ART registration, pharmaceutical services oversight, and evaluating community health systems, all supported by technical proficiency in database management and network maintenance. Let's connect and discuss how my experience can drive success and innovation in healthcare analytics and decision-making.<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/samuel-dribsa/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
